package com.reactnativejnibridge

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.ReactApplicationContext

/**
 * MyPackage is the manifest for all custom native code in this app.
 *
 * WHY IT EXISTS
 * React Native discovers native modules and native view managers through
 * [ReactPackage] implementations. A package is a simple container that answers
 * two questions: "which native functions can JS call?" and "which native views
 * can JS render?". Without being registered in a ReactPackage, a module or view
 * manager is invisible to the JS side — NativeModules.JniBridge would be
 * undefined and requireNativeComponent('VideoPlayer') would throw.
 *
 * WHAT IT DOES
 * [createNativeModules] returns the list of [ReactContextBaseJavaModule] instances
 * that expose callable methods to JavaScript. Each module's getName() return value
 * becomes the key under NativeModules on the JS side.
 *   → [JniBridgeModule] registers as NativeModules.JniBridge
 *
 * [createViewManagers] returns the list of [SimpleViewManager] / [ViewGroupManager]
 * instances that map to React components created via requireNativeComponent().
 * Each manager's getName() return value becomes the component name on the JS side.
 *   → [VideoPlayerViewManager] registers as requireNativeComponent('VideoPlayer')
 *
 * HOW IT IS REGISTERED
 * This package is added manually in MainApplication:
 *   PackageList(this).packages.apply { add(MyPackage()) }
 * It cannot use autolinking because autolinking is only available for npm packages
 * that ship a react-native.config.js. App-level native code must always be
 * registered by hand.
 *
 * NEW ARCHITECTURE NOTE
 * In New Architecture mode the [createNativeModules] method is technically
 * deprecated in favour of per-module TurboModule specs generated by codegen.
 * However, React Native 0.86 ships an interop layer that wraps any
 * [ReactContextBaseJavaModule] returned here into a TurboModule adapter
 * automatically, so no codegen spec file is required for this use case.
 * The same interop applies to view managers returned by [createViewManagers].
 */
class MyPackage : ReactPackage {
    override fun createNativeModules(context: ReactApplicationContext) =
        listOf(JniBridgeModule(context))

    override fun createViewManagers(context: ReactApplicationContext) =
        listOf(VideoPlayerViewManager())
}
